export const FETCH_OFFERS = 'FETCH_OFFERS';
export const FETCH_OFFERS_START = 'FETCH_OFFERS_START';
export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS';
export const FETCH_OFFERS_FAIL = 'FETCH_OFFERS_FAIL';

export const FETCH_OFFER = 'FETCH_OFFER';
export const FETCH_OFFER_START = 'FETCH_OFFER_START';
export const FETCH_OFFER_SUCCESS = 'FETCH_OFFER_SUCCESS';
export const FETCH_OFFER_FAIL = 'FETCH_OFFER_FAIL';

export const POST_OFFER = 'POST_OFFER';
export const POST_OFFER_START = 'POST_OFFER_START';
export const POST_OFFER_SUCCESS = 'POST_OFFER_SUCCESS';
export const POST_OFFER_FAIL = 'POST_OFFER_FAIL';
export const POST_OFFER_CLEAR = 'POST_OFFER_CLEAR';
